// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:9962f33b-b234-446a-872b-e555ea2a8cf9",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_Fao3rmqpl",
    "aws_user_pools_web_client_id": "5p1k5lvljfflfi9flp4h88ambo",
    "aws_user_files_s3_bucket": "vpgrnaturalistapp800eaa5eeca94bbcbc500b393d90fb46",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
